export const recipies: Recipe[] = [
    {
        id: "1",
        name: "Pasta",
        description: "Pasta with tomato sauce",
        ingredients: ["pasta", "tomato sauce"],
        steps: ["Boil pasta", "Add tomato sauce"],
        image: "/images/hero.png",
        category: "Italian",
        featured: true,
        rating: 4.0,
    },
    {
        id: "2",
        name: "Pizza",
        description: "Delicious pizza with various toppings",
        ingredients: [
            "dough",
            "tomato sauce",
            "cheese",
            "pepperoni",
            "mushrooms",
            "bell peppers",
        ],
        steps: [
            "Roll out the dough",
            "Spread tomato sauce on the dough",
            "Sprinkle cheese on top",
            "Add desired toppings",
            "Bake in the oven",
        ],
        image: "/images/hero.png",
        category: "Italian",
        featured: false,
        rating: 4.5,
    },
    {
        id: "3",
        name: "Sushi",
        description: "Traditional Japanese sushi rolls",
        ingredients: ["sushi rice", "nori seaweed", "fish", "vegetables"],
        steps: [
            "Prepare sushi rice",
            "Lay out nori seaweed",
            "Add rice and desired fillings",
            "Roll tightly",
            "Slice into bite-sized pieces",
        ],
        image: "/images/hero.png",
        category: "Japanese",
        featured: false,
        rating: 4.2,
    },
    {
        id: "4",
        name: "Burger",
        description: "Classic beef burger with all the fixings",
        ingredients: [
            "ground beef",
            "buns",
            "lettuce",
            "tomato",
            "onion",
            "cheese",
            "pickles",
        ],
        steps: [
            "Form ground beef into patties",
            "Grill or cook on stovetop",
            "Toast buns",
            "Assemble burger with toppings",
        ],
        image: "/images/hero.png",
        category: "American",
        featured: true,
        rating: 4.9,
    },
    {
        id: "5",
        name: "Curry",
        description: "Spicy and flavorful curry dish",
        ingredients: [
            "curry paste",
            "coconut milk",
            "meat or vegetables",
            "spices",
        ],
        steps: [
            "Heat curry paste in a pan",
            "Add coconut milk and simmer",
            "Add meat or vegetables",
            "Cook until tender",
            "Serve with rice",
        ],
        image: "/images/hero.png",
        category: "Indian",
        featured: true,
        rating: 4.8,
    },
    {
        id: "6",
        name: "Tacos",
        description: "Tasty Mexican tacos with various fillings",
        ingredients: [
            "tortillas",
            "meat or beans",
            "salsa",
            "guacamole",
            "cheese",
            "lettuce",
        ],
        steps: [
            "Warm tortillas",
            "Cook meat or beans",
            "Assemble tacos with fillings",
            "Top with salsa, guacamole, cheese, and lettuce",
        ],
        image: "/images/hero.png",
        category: "Mexican",
        featured: true,
        rating: 4.3,
    },
    {
        id: "7",
        name: "Stir Fry",
        description: "Quick and healthy stir fry dish",
        ingredients: [
            "protein (chicken, beef, tofu)",
            "vegetables",
            "soy sauce",
            "garlic",
            "ginger",
        ],
        steps: [
            "Heat oil in a pan",
            "Cook protein until browned",
            "Add vegetables and stir fry",
            "Season with soy sauce, garlic, and ginger",
        ],
        image: "/images/hero.png",
        category: "Asian",
        featured: false,
        rating: 4.1,
    },
    {
        id: "8",
        name: "Lasagna",
        description: "Layers of pasta, meat, and cheese",
        ingredients: [
            "lasagna noodles",
            "ground beef",
            "tomato sauce",
            "ricotta cheese",
            "mozzarella cheese",
        ],
        steps: [
            "Cook lasagna noodles",
            "Brown ground beef",
            "Layer noodles, meat, sauce, and cheese",
            "Bake in the oven",
        ],
        image: "/images/hero.png",
        category: "Italian",
        featured: true,
        rating: 4.4,
    },
    {
        id: "9",
        name: "Sushi Bowl",
        description: "Deconstructed sushi in a bowl",
        ingredients: [
            "sushi rice",
            "fish or tofu",
            "vegetables",
            "soy sauce",
            "sesame seeds",
        ],
        steps: [
            "Prepare sushi rice",
            "Slice fish or tofu",
            "Arrange rice, fish, and vegetables in a bowl",
            "Drizzle with soy sauce",
            "Sprinkle with sesame seeds",
        ],
        image: "/images/hero.png",
        category: "Japanese",
        featured: false,
        rating: 4.6,
    },
    {
        id: "10",
        name: "Chicken Parmesan",
        description: "Breaded chicken topped with marinara sauce and cheese",
        ingredients: [
            "chicken breasts",
            "breadcrumbs",
            "marinara sauce",
            "mozzarella cheese",
            "parmesan cheese",
        ],
        steps: [
            "Coat chicken in breadcrumbs",
            "Cook chicken until golden brown",
            "Top with marinara sauce and cheese",
            "Bake in the oven until cheese is melted and bubbly",
        ],
        image: "/images/hero.png",
        category: "Italian",
        featured: true,
        rating: 4.7,
    },
];

export const categories: Category[] = [
    {
        id: "1",
        name: "Beverages",
        image: "/images/beverages.jpeg",
    },
    {
        id: "2",
        name: "Appetizers",
        image: "/images/appetizers.jpeg",
    },
    {
        id: "3",
        name: "Deserts",
        image: "/images/deserts.jpeg",
    },
    {
        id: "4",
        name: "Salads",
        image: "/images/salads.jpeg",
    },
    {
        id: "5",
        name: "Main Course",
        image: "/images/hero.png",
    },
];
